### ISSUE TITLE
Specialize IBMQBackend for pulse

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#109]
### What is the expected behavior?

In a similar spirit to the `IBMQSimulator` specialization, since terra 0.8 there are pulse-specific constructs that we can make use of.

We should check with the pulse team and decide on the best way to take advantage of the new functionality, aiming for being specific and separating functionality - a plausible approach might be:

* creating new `IBMQBackend` subclasses for pulse-enabled devices and simulators, based on the open pulse flag in the configuration
* make use of the right subclasses in their methods (`Configuration`, `Qobj`)
* adjust the methods that are only relevant to one of the types (`.defaults()` - see also #108)

**Comment by jyu00** [comment]
@diego-plan9 As discussed, I don't think there is a need for a new open pulse `IBMQBackend` subclass (for now anyway), since almost all of the function calls are identical. In addition, it'd get slightly complicated with an open pulse simulator, since it inherits both open pulse and simulator traits.

**Comment by diego-plan9** [comment]
Thanks @jyu00 - seems good for now!
