### ISSUE TITLE
Revise WebSockets interaction with Jupiter Notebooks

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#120]
### What is the expected behavior?

Our current implementation of WebSockets is based on `asyncio`, which causes some issues with Jupyter Notebooks since the control of the event loop is directly managed by Jupyter (see https://github.com/jupyter/notebook/issues/3397).

We should revise the implementation deciding between:
* not attempting to start the event loop manually (probably the preferred solution), and instead try to add the task if it is already running
* use another package that allows nesting event loops (might have some implications in the complexity and side effects)
* as a last resort, verify that Exceptions raised from the WebSockets module are handled gracefully, triggering the http-only pooling as a fallback

**Comment by delapuente** [comment]
Option 1 is impossible without `await`-ing. The user should explicitely `await` for the result:

```python
result = await job.result()
```

This is not a trivial API change. First, it affects the specification since `job.result()` will no longer be blocking. Second, `job.result()` cannot be overloaded since it needs to by an `async` method which forces a non awaitable result into a `Future`.
