### ISSUE TITLE
IBMQJob status [or equiv job.result()] should not fail if device woken from sleep

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#207]
### What is the expected behavior?
Currently, creating a job and calling `job.result()` will raise an exception if you put your computer to sleep before the job is done.  This is because it takes a finite amount of time (infinite if on the IBM network) to reconnect to the network, and the job throws a connection error.  It would be nice if the job tried once, and if failed, try a couple times at 5 sec intervals, or the like, to allow the network connection to be re-established.

**Comment by luisg5** [comment]
Some time ago, [functionality](https://github.com/Qiskit/qiskit-ibmq-provider/pull/341) was added to the websocket client so it retries up to five times (with time in between) if the websocket connection closes while getting the status of the job. This is used in the result path, since it waits for the job to reach a final status before attempting to get its result. 

Would there need to be something else added to address this issue or does the websocket implementation cover it?

**Comment by nonhermitian** [comment]
I actually just ran into this again last night.  Putting the computer to sleep for sometime, and then opening immediately raised a gaierror exception.

**Comment by luisg5** [comment]
After some testing, it seems like the retry logic takes effect when there is a connection problem or the laptop is put to sleep. However, it may not be apparent to the user when either of these occur, since the logged messages might not be displayed in the console. Messages not displaying in the console would be due to the the low level they are logged at.

In this case, all the user would end up seeing is the final exception that is raised, which stems from a `gaierror`, since a connection could not be established. After modifying the logging levels, it should be more apparent to the user when a connection error occurred or a retry was attempted.

**Comment by luisg5** [comment]
After doing some testing, it seems like the retry logic takes effect when there is a connection problem or the laptop is woken up from sleep and trying to establish a connection. However, it might not be apparent because logged messages might not be displayed in the console due to their low logging level.

As of now, if the maximum number of retries is exhausted, the only thing displayed in the console is the final exception, which stems from a `gaierror` since no connection could be established. After modifying the logging levels, it would be more apparent when a connection error occurs or a retry attempt is made.

**Comment by luisg5** [comment]
If the connection problem occurs however, it might be worth increasing the time between retries?

**Comment by luisg5** [comment]
Closed since #537 attempts to make it more apparent when the maximum number of retries are exhausted. If the problem persists, such as the retry mechanism does not take place, then comment here so the reissue could be reevaluated and opened.
