### ISSUE TITLE
With multiple IBMQE accounts, ambiguity in the backend selection

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-ibmq-provider#233]
### Information

- **Qiskit IBMQ Provider version**:  'qiskit-ibmq-provider': '0.2.3rc1',
- **API URL or version**: 

- **Python version**:
- **Operating system**: using the `https://quantum-computing.ibm.com/jupyter/`

### What is the current behavior?

When a user have multiple credentials (with IBMQE), it seems the name is too ambiguous.

### Steps to reproduce the problem

```
> IBMQ.backends()
[<IBMQBackend('ibmq_20_tokyo') from IBMQ(ibm-q-dev, qiskit, terra)>,
 <IBMQBackend('ibmq_poughkeepsie') from IBMQ(ibm-q-dev, qiskit, terra)>,
 <IBMQSimulator('ibmq_qasm_simulator') from IBMQ(ibm-q-dev, qiskit, terra)>,
 <IBMQSimulator('ibmq_qasm_simulator') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmqx4') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmqx2') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmq_16_melbourne') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmqx4') from IBMQ()>,
 <IBMQSimulator('ibmq_qasm_simulator') from IBMQ()>,
 <IBMQBackend('ibmqx2') from IBMQ()>,
 <IBMQBackend('ibmq_16_melbourne') from IBMQ()>]

> IBMQ.get_backend('ibmqx2')

/opt/conda/lib/python3.7/site-packages/qiskit/providers/baseprovider.py in get_backend(self, name, **kwargs)
     49         backends = self.backends(name, **kwargs)
     50         if len(backends) > 1:
---> 51             raise QiskitBackendNotFoundError('More than one backend matches the criteria')
     52         elif not backends:
     53             raise QiskitBackendNotFoundError('No backend matches the criteria')
```

### What is the expected behavior?

The backend is technically the same. It should be a single entry in `backends`, I think.

**Comment by 1ucian0** [comment]
BTW, `%qiskit_backend_overview` shows `ibmqx2` once.

**Comment by nonhermitian** [comment]
That is because the backend overview only looks at the first backend given when there are duplicate names.

I think the above issue gets cleared up automatically in the new provider interface.

**Comment by diego-plan9** [comment]
This is the behaviour "by design" in pre-0.3 versions - in the Jupyter interface, all the hubs are loaded by default, and if you end up having backends with the same name you need to use the filtering included in `.get_backend()` and `.backends()`:

```
IBMQ.get_backend('ibmqx2', hub='somehub')
```

As @nonhermitian mentions, in the upcoming release access to the backends will be done via single providers that only give access to one single hub, eliminating the ambiguity. Some more information can be found [in the README](https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/README.md#updating-your-programs) - the short version is that, in this case, a backend without ambiguity would be obtained by:

```
p = IBMQ.get_provider(hub='somehub')
p.get_backend('ibmqx2') 
```
