### ISSUE TITLE
test/ibmq/test_registration.py not working due to interface changes in latest release

### ISSUE THREAD

**Issue by jlatone** [Qiskit/qiskit-ibmq-provider#24]
### Informations

- **Qiskit version**: terra 0.7.0
- **Python version**: python 3.7.2
- **Operating system**: macos mojave 10.14.2 (18C54)

### What is the current behavior?
Test test/ibmq/test_registration.py not working.

### Steps to reproduce the problem
LOG_LEVEL=INFO python -m unittest test/ibmq/test_registration.py

### What is the expected behavior?
Run all tests OK 

### Suggested solutions
FIx code in test so it's up to date with latest release.

**Comment by jlatone** [comment]
Hi @diego-plan9, this was a simple change for a few variables like "qconfig" being changed to "_qconfig." 

I have 2 separate environments, 1 from the official release version and 1 from clones of forked qiskit projects. This change was from/for the latter...and I think(?) it's ok. I see I messed up when I wrote "terra 0.7.0." I should have said "terra 0.8.0" as printed from this: 
    from qiskit import __version__ as qiskit_terra__version__
    print(qiskit_terra__version__)

**Comment by jlatone** [comment]
Just fyi, here's the origin of the issues I've been raising: I've been merely forking/cloning/building/testing the qiskit projects, one-by-one, following instructions in CONTRIBUTING, and if I happen to encounter any small errors I've been fixing them.

**Comment by diego-plan9** [comment]
> I've been merely forking/cloning/building/testing the qiskit projects, one-by-one, following instructions in CONTRIBUTING, and if I happen to encounter any small errors I've been fixing them.

And that is much appreciated, thanks a lot for your contributions and the effort!

In this case, however, the renaming of the modules (ie. removing the `_`) was intentional, and it seems to point at some mismatch between the versions in your environments. All the `qiskit/providers/ibmq` and `test/*/ibmq` files are now part of this repository (as in, they are not present in `terra` master), and it seems that the "old" ones are being picked up during the test run you mentioned at the beginning at the issue. Can you double-check which files are really being loaded in the environment where you have all the `master` versions (making sure the latest `master` is fetched)?

Some useful commands might be:
* `pip freeze`  and `pip show qiskit-terra` (for making sure no old version is installed that might conflict)
* `import qiskit; qiskit.__file__` (to ensure which file is actually in use in your env)

**Comment by jlatone** [comment]
You described the error I thought I was avoiding. My setup is pretty standard--fork & clone--so something must be amiss. `pip show qiskit-terra` before I run test_registration.py shows 0.8.0. But, I do appear to have a **ibmq/test_registration.py** file in both my qiskit-terra and qiskit-ibmq-provider forked master clones.

I'm going to punt on what I was attempting, and simply ask: What's the recommended way for someone to work with the latest of all of qiskit from what's public on github, e.g., the master branch of qiskit-terra, qiskit-ibmq-provider, qiskit-aer, and qiskit-aqua? Is there a set of commands one could run from a new conda environment that will fork/clone, make/build, test, intslal, and verify an installation?

**Comment by diego-plan9** [comment]
> But, I do appear to have a ibmq/test_registration.py file in both my qiskit-terra and qiskit-ibmq-provider forked master clones.

Hmm, that might give a hint towards what could be causing the issues you are experiencing - can you check if your master contains the commit `b8bcd9a`? That was the PR where the files were removed from terra - if it is not showing on your `git log`, `git pull upstream master` (from your local terra clone) hopefully would do the trick.

The closest instructions for working on several repositories at the same time is probably on the comment above (https://github.com/Qiskit/qiskit-ibmq-provider/issues/24#issuecomment-456577073)! But yes, I agree it is probably a good time to make it a bit more formal and document it in a more accessible place - I'll create an issue for finding out the best place to put that content and populate it accordingly :+1:

**Comment by diego-plan9** [comment]
Great, glad it worked! Let's close the issue and keep track of adding the instructions to the documentation at https://github.com/Qiskit/qiskit/issues/48
