### ISSUE TITLE
All providers have a circuits attribute

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#247]
### Information

- **Qiskit IBMQ Provider version**: master
- **API URL or version**:

- **Python version**:
- **Operating system**:

### What is the current behavior?
Circuits (and other entitlements) are not part of a provider by default, but are only available if an user has access.  Otherwise the provider should not list those items.

### Steps to reproduce the problem

```python

from qiskit import IBMQ
IBMQ.load_account()
pro = IBMQ.get_provider(group='open')
pro.circuits.hardware_efficient()
```

**Comment by diego-plan9** [comment]
Yes, this is by design in this iteration, as per the proposal and due to current API design (see #98 ). Note that even if the interface is present, the execution of the circuits will not be available for users that do not have that entitlement currently. I agree that eventually would be nice to move to a more dynamic mechanism, but is probably still a bit far away.

**Comment by nonhermitian** [comment]
Ok, as long as this is on the radar, then I will close this.  Thanks
