### ISSUE TITLE
Allow staging tests to run on more than just staging

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#374]
### What is the expected behavior?
PR #360 moved some slow tests to run on staging system. There is no good way right now to run them on non-staging aside from updating the code. Ideally we'd want to be able to run them on either. This can be accomplished by introducing more environment variables, or maybe we can consider moving to `pytest`.

**Comment by luisg5** [comment]
While working on #420 , I've also been thinking of different ways to try and address #374. I'm currently working on something, but its still a WIP. 

Since we would want to have the staging tests run on a production device as well, regardless of whether it runs on staging or not, it seems that we would have to change the functionality of the `run_on_staging` decorator. Namely, we would have to change it so that the test is not skipped if the staging credentials are not present. One possibility I've been working on is to have it return the staging provider (if the staging credentials are set) or `None` (if the staging credentials are not set). This would allow it to be used by `requires_device[s]`, which could append a `backends` argument to the tests decorated with it.

Would it be feasible to move in this direction? I know pytest has also been mentioned as an alternative.
