### ISSUE TITLE
Error code should be first in error_message

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#468]
### Information

- **Qiskit IBMQ Provider version**: latest
- **API URL or version**:

- **Python version**:
- **Operating system**:

### What is the current behavior?
The error code should be first in the `error_message` so that one can quickly identify it.  Currently it is at the end:
```
'The number of shots in the Qobj (9000) is higher than the number of shots of shots supported by the device (8192). Error code: 603.'
```

**Comment by jyu00** [comment]
The users should be able to ignore the error codes most of the time, as they should be able to get all the information from the error messages. Since the message is the more important and informative part, I think it should go first.

**Comment by nonhermitian** [comment]
So the pattern of generic message first, then specific string is a common one. e.g. see the way Python throws exceptions.  However, more importantly, the error codes are the unique identifiers, not the remaining string.  The remaining specific strings may change, or may not be understood by non-native English speakers.  The error codes are searchable in the Qiskit documentation, and can be translated into other languages by the community translation teams, as well as provide more detailed help when needed.

This also brings up another point that perhaps it would be nice to include the link to the relevant issue on qiskit.org, as identified by the unique number code, in the error message string itself.

**Comment by jyu00** [comment]
I agree the error code would be useful for search & non-English speakers. Telling the users that the error code is a 4-digit number at the very end of the message should pretty clear, even if they don't understand anything in the error message string. And having an informative message first, instead of an error code they need to search on, would be nice to users who can read the message. 

It'd be nice to have links to relevant issues/stackexchange, but I don't think inside the error message is the best place. Links and linked page content can get stale, and any updates to error messages require qiskit release and user action. Perhaps the qiskit documentation page with the error information can have the links, and the error messages can have links to that qiskit page.

**Comment by nonhermitian** [comment]
Closing this as not worth acting upon anymore, i.e. I lost the argument.
