### ISSUE TITLE
Handle partial success in jobs

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-ibmq-provider#49]
### What is the expected behavior?
A job can partially succeed if not all their experiments fail. The current implementation does not allow the user to retrieve the successful experiments. Instead, it raises an error when trying to get the results.

```
>> job.status()
<JobStatus.ERROR: 'job incurred error'>
>> job.result()
JobError: 'Invalid job state. The job should be DONE but it is JobStatus.ERROR'
```

We should be able to browse a partial success, even if the global status of the job is `ERROR`.

**Comment by jyu00** [comment]
This does seem to be a useful feature, but it would only apply to the simulators since real backends don't return partial results. The main issue is that the results returned by the simulators are not schema compliant if some of the experiments had failed. For example, a partially successful job result might look like 

```
 {'backend_name': 'ibmq_qasm_simulator',
 ...
 'results': [{'status': 'ERROR: Circuit contains invalid instructions ( '
                        'invalid gate instructions: {test_name})',
              'success': False},
             {'data': {'counts': {'0x0': 122, '0x3': 134}},
              'header': {...},
              'shots': 256,
              'status': 'DONE',
              'success': True],
 'status': 'COMPLETED',
 'success': False,
 'time_taken': 0.003798207}
```

The first experiment in the above example is missing required fields `data` and `shots`, therefore we cannot easily convert it to a `qiskit.Result` object.  If we want to implement this, we can either 1) manipulate the data to make it schema compliant or 2) ask the simulator teams to return schema compliant results for failed experiments or 3) loosen the schema to not require `data` and `shots`. 

@diego-plan9 Any thoughts?

**Comment by jyu00** [comment]
The test case that generates an error can be found [here](https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/test/ibmq/test_ibmq_job.py#L375)

**Comment by diego-plan9** [comment]
@luisg5 , @jyu00 - can you check if we can close this issue?

**Comment by luisg5** [comment]
The issue should not be closed yet. Although the qasm simulator from the latest Aer release supports partial results, the results returned from the API are still not schema complaint.

Since this is the case, running a job (where some experiments succeed and others fail) will currently cause an `IBMQJobFailure` exception.

**Comment by diego-plan9** [comment]
Ok - changing the milestone accordingly, so we can retake the issue after the fixes are in place in the remote components.

**Comment by luisg5** [comment]
The remote components are now able to successfully return partial results for `ibmq_qasm_simulator`.
