### ISSUE TITLE
Cannot transpile multiple circuits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#712]
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

backend = provider.backends.ibmq_vigo
qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])

new_circs = transpile([qc, qc], backend)
```

gives:

/opt/miniconda3/lib/python3.7/site-packages/qiskit_terra-0.15.0-py3.7-macosx-10.9-x86_64.egg/qiskit/compiler/transpile.py:445: UserWarning: All timestamps in backend properties are now in local time instead of UTC.
  if backend.properties():
Process ForkProcess-1:
Process ForkProcess-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/miniconda3/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/opt/miniconda3/lib/python3.7/concurrent/futures/process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "/opt/miniconda3/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() missing 10 required positional arguments: 'n_uchannels', 'u_channel_lo', 'meas_levels', 'qubit_lo_range', 'meas_lo_range', 'dt', 'dtm', 'rep_times', 'meas_kernels', and 'discriminators'
TypeError: __init__() missing 10 required positional arguments: 'n_uchannels', 'u_channel_lo', 'meas_levels', 'qubit_lo_range', 'meas_lo_range', 'dt', 'dtm', 'rep_times', 'meas_kernels', and 'discriminators'

**Comment by mtreinish** [comment]
@jyu00 and I did some more digging this morning and I got to the root cause. It was introduced by: https://github.com/Qiskit/qiskit-terra/commit/41cf87c59a2c3381e0c8190f022058356aa8f586 which is forcing the backend object to be passed across `parallel_map` which is causing issues like this it's also breaking docs jobs in ignis when they try to transpile circuits in a jupyter execute. I'm going to push up a revert for that.

**Comment by chriseclectic** [comment]
Just to add: this issue seems to be what is causing the doc-build in Ignis CI to fail because of jupyter-execute cells that hang for over 60 minutes when trying to transpile a list of circuits.  In the example transpiling was from an execute call for the QasmSimulator backend with optimization_level=0, so transpiling in this particular case should just return the input circuit unchanged.

**Comment by chriseclectic** [comment]
I wonder if it has something to do with Aer QasmSimulator. Running the following simple example I get:

```python
from qiskit import transpile, QuantumCircuit, Aer, BasicAer
from qiskit.providers.aer import QasmSimulator
qc = QuantumCircuit(1)

# This is ok
transpile([qc, qc])

# This is also ok
transpile([qc, qc], backend=BasicAer.get_backend('qasm_simulator'))

# This hangs and never finishes
transpile([qc, qc], backend=Aer.get_backend('qasm_simulator'))
```

**Comment by mtreinish** [comment]
@chriseclectic Yeah, my guess is it's a python hanging trying to pickle an object form c++. What happens if you just try to pickle a `QasmSimulator` object and then try to pickle load that? Like:

```python3
import pickle
from qiskit.providers.aer import QasmSimulator
backend = QasmSimulator()
pkl = pickle.dumps(backend)
pickle.loads(pkl)
```

That's what was introduced to transpile with >1 circuit by Qiskit/qiskit-terra#4110 (by adding transpile as a parallel arg). Regardless I pushed up a revert for it in https://github.com/Qiskit/qiskit-terra/pull/4723. This close to a terra release we shouldn't be spending time trying to fix things like this. That can be something for 0.16.0
