### ISSUE TITLE
ID gates should be replaced by delay instructions

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-ibmq-provider#906]
### What is the expected enhancement?
Qiskit now supports delay instructions. The `IDGate` was always a way of hacking delays into quantum circuits that will be run on physical backends. Since the delay is now explicitly supported it should replace the IDGate when used in a circuit. This will enable backends to no longer return the `id` gate as a basis gate in the long run.

**Comment by kdk** [comment]
After discussion with @taalexander , we came to the conclusion that the IBMQ provider is the best place to warn users and transition away from `id` instruction, since this is a change in IBMQ backend behavior.

**Comment by taalexander** [comment]
Any update on how this will work in the provider?

**Comment by jyu00** [comment]
@taalexander The easiest choice is during `assemble` (or its replacement if we get to that point), since that's the only place we touch the circuits. Either way I hope this is not high priority since I probably won't get to it anytime soon, unless I get some help ;)

**Comment by ajavadia** [comment]
I think in the compiler we can write a pass that either leaves ID intact (if it is in basis) or converts to delay. So backends that still have ID will continue to receive ID. Those that have transitioned to delay will receive delay. No backend should remove ID without adding delay otherwise it just breaks the ability to control timing. But as it stands the ID->Delay change is basically the same as U -> SX change which was also handled in the compiler.

The compiler would know the duration of delay by looking up `backend.properties().gate_duration(SXGate(), qubit)`  with a unit of `dt`.

**Comment by nonhermitian** [comment]
> The compiler would know the duration of delay by looking up backend.properties().gate_duration(SXGate(), qubit) with a unit of dt.

This seems particularly IBM centrist to me.  Why can't `delay` have a `None` value that gets populated by whatever the backend says should be default rather than hardcoded to a particular basis gate?

I agree the compiler can handle the rest.
