### ISSUE TITLE
Submitted jobs stuck in the validation phase

### ISSUE THREAD

**Issue by RiccardoRoma** [Qiskit/qiskit-ibmq-provider#907]
### Informations

- **Qiskit version**: 0.23.1
- **Python version**: 3.7.6
- **Operating system**: Windows 10

### What is the current behavior?
When submitting a job or a batch of jobs to a IBMQbackend using the IBMQJobManager sometimes the single job gets stuck in the validation phase. This happens randomically, it seems to happen more frequently for tomographies or jobs consisting of a great number of circuits. The problem isn't the circuit because a resubmit doesn't encounter this problem.
For example:
![issue](https://user-images.githubusercontent.com/64189523/104647842-ba9dc000-56b2-11eb-8a49-5fcf66225866.PNG)

### Steps to reproduce the problem
1) Initialize a QuantumCircuit or a list of circuits
2)Use the IBMQJobManager to submit a job or a batch of jobs to a backend

### What is the expected behavior?
The job should be convalidated and executed.

### Suggested solutions
This seems to be a problem in the management of jobs. I have no idea about how to solve it.

**Comment by jyu00** [comment]
@RiccardoRoma Thank you for reporting the issue! 

If a job is in `VALIDATING` state, that means it has landed on the IBM Quantum cloud server. Unfortunately that means there is little that can be done from the client (Qiskit) side other than resubmitting. The errors you saw were likely due to outage on the server side.

If you encounter this again, please contact IBM Quantum support, via Slack or IBM Quantum Experience (click on the question mark on the top right corner, then select `Feedback` and `Report a bug or issue`). If you give them the job ID, an admin might be able to re-queue the job for you.

**Comment by RiccardoRoma** [comment]
Thank you for taking the time to inspect this issue.
Riccardo Roma

Il ven 26 mar 2021, 21:31 Jessie Yu ***@***.***> ha scritto:
