### ISSUE TITLE
update job share level after execution

### ISSUE THREAD

**Issue by alexgalda** [Qiskit/qiskit-ibmq-provider#914]
### What is the expected behavior?
Having a command to update the share_level property of a job in the remote database after its execution.

**Comment by rathishcholarajan** [comment]
I am working on this and will have a PR up soon :)

**Comment by jyu00** [comment]
@alexgalda Unfortunately the job sharing feature was disabled on IBM Quantum a while ago due to low adoption. Qiskit was just never updated to reflect that (fixed in #970). If you still want this feature, please work with your IBM Quantum representative, if you have one, or request it on https://quantum-computing.ibm.com/ (click on the question mark on the upper right corner then select Feedback and Missing Feature as the topic).
