### ISSUE TITLE
IBM real quantum computer and simulator produce completely different results

### ISSUE THREAD

**Issue by DevelopDaily** [Qiskit/qiskit-ibmq-provider#928]
### Information

- **Qiskit IBMQ Provider version**: The latest on the IBM Quantum Lab
- **Python version**: The latest on the IBM Quantum Lab
- **Operating system**: The latest on the IBM Quantum Lab

### What is the current behavior?

The real quantum computer **_ibmq_16_melbourne_**  and the _**ibmq_qasm_simulator**_ produce completely different results, the latter being correct.

### Steps to reproduce the problem

I upload the circuit in QASM and you can run it on the IBM Quantum Lab.

### What is the expected behavior?

The results should be roughly same.

### Suggested solutions

Could you please check if your real quantum computers are working properly?

![Bad_Good](https://user-images.githubusercontent.com/54299975/116939326-285a0180-ac3a-11eb-9578-20d63cf52608.jpg)
[qpe_unitary_anc0.zip](https://github.com/Qiskit/qiskit-ibmq-provider/files/6418046/qpe_unitary_anc0.zip)

**Comment by jyu00** [comment]
Hi @DevelopDaily, since this is not a `qiskit-ibmq-provider` related issue, please open a bug report with IBM Quantum directly. You can do so by going to https://quantum-computing.ibm.com/ , click on the question mark on the upper right corner, select `Feedback`,  then `Report a Bug or Issue` as the topic. Thank you for your help. 



![image](https://user-images.githubusercontent.com/28284230/117681892-8e85dd80-b180-11eb-8c49-138673f63bbd.png)


![image](https://user-images.githubusercontent.com/28284230/117699347-bc741d80-b192-11eb-9e5d-f057f1aa637f.png)
