### ISSUE TITLE
Need scikit-quant for new optimizer coder tests

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#986]
### Information

- **Qiskit IBMQ Provider version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The [CI run](https://github.com/Qiskit/qiskit-ibmq-provider/runs/3006356704?check_suite_focus=true) failed last night because the optimizer tests required `scikit-quant`.

**Comment by jyu00** [comment]
@Rcuz8 is working on this, even though Github doesn't let me assign it to him for some reason.

**Comment by rathishcholarajan** [comment]
Found this:
https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees

"You can assign up to 10 people to each issue or pull request, including yourself, anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members with read permissions to the repository."

So I guess if @Rcuz8 commented on this pull request we'd be able to assign to him. But since Ryan's on our team I have invited him as collaborator which should let us assign to him once he accepts.

**Comment by jyu00** [comment]
Closed by #981
