### ISSUE TITLE
test_run_circuit error (cron-staging)

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibmq-provider#993]
### Information

- **Qiskit IBMQ Provider version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
This [Cron-staging run](https://github.com/Qiskit/qiskit-ibmq-provider/runs/3043256876?check_suite_focus=true#step:5:2028) errored in test_run_circuit.

### Steps to reproduce the problem
NA

### What is the expected behavior?
Test should pass.

### Suggested solutions
TBD

**Comment by jyu00** [comment]
This is because #977 switched to using `qpy` to serialize a QuantumCircuit. `qpy` is in `qiskit-terra` master and hasn't been released, so #977 put in code to skip serialization if qiskit-terra version is <0.18. Since this test runs on qiskit-terra stable, not master, it failed to serialize QuantumCircuit. The error should go away once qiskit-terra releases.

**Comment by rathishcholarajan** [comment]
No longer see this error in Cron-staging. Closing.
